[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "local-pkgs"
version = "0.2.1"
requires-python = ">=3.10"

[tool.setuptools.packages.find]
where = ["."]
include = ["local_pkgs*"]  # <-- this tells setuptools to package local_pkgs/